# Generated by Django 5.1.7 on 2025-04-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contact_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
