# Generated by Django 5.1.7 on 2025-04-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
