# Generated by Django 5.1.7 on 2025-04-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('webapp', 'Web App'), ('mobileapp', 'Mobile App'), ('aiml', 'AI/ML')], max_length=20)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnails/')),
                ('preview_image', models.ImageField(upload_to='portfolio/previews/')),
                ('details_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
