# Generated by Django 5.1.7 on 2025-04-02 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='details_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='projects/main_images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
        ),
    ]
