# Generated by Django 5.1.7 on 2025-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_project_details_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
