# Generated by Django 5.1.7 on 2025-04-03 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_category_remove_project_category_project_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('webapp', 'Web App'), ('mobileapp', 'Mobile App'), ('aiml', 'AI/ML')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
